### ISSUE TITLE
Can not bind mouse buttons.

### ISSUE THREAD

**Issue by SteveWinst10** [luttje/KeyToJoy#1]
I want to use the mouse buttons for the triggers but cannot do so.

**Comment by luttje** [comment]
Hi there!

Thanks for your interest, I quickly created [an update](https://github.com/luttje/KeyToJoy/releases/tag/0.3.2-alpha) that should support binding to mouse buttons (currently only left, middle and right)

I have not tested it very well, but it seems to work.

In case you get stuck (from overriding a mouse button): abort the overriding of buttons with <kbd>Left Ctrl</kbd> + <kbd>Left Shift</kbd> + <kbd>Esc</kbd>

Please let me know if there's any problems
