### ISSUE TITLE
How to simulate output gamepad button with script

### ISSUE THREAD

**Issue by nxoet** [luttje/KeyToJoy#15]
When I use the keyboard to emulate the gamepad, I definitely want the script to emulate the gamepad keys, but now I don't know the code corresponding to the gamepad keys, and i cheack the "Scripting API Reference", there's 404.

**Comment by luttje** [comment]
Okay I see what's going wrong. I made a mistake. I will fix this within a couple hours.

I will also try to get a Delay function working, [similar to what you posted in your script](https://github.com/luttje/KeyToJoy/pull/3#issuecomment-1162577110), since you will probably want to use that.

**Comment by luttje** [comment]
I quickly made some improvements and updated the documentation: https://github.com/luttje/KeyToJoy/releases/tag/0.4.0

Let me know if you find any more issues with this. For now I will close this.

**Comment by nxoet** [comment]
> I quickly made some improvements and updated the documentation: https://github.com/luttje/KeyToJoy/releases/tag/0.4.0
> 
> Let me know if you find any more issues with this. For now I will close this.

Sorry, I still don't know how to achieve what I want, can you make an example like: press "F" on the keyboard to achieve the action of pressing the →↓←+○ on the gamepad.

**Comment by luttje** [comment]
I see that more documentation is still required. I will work on that.

For now I will make an example for you:
> press "F" on the keyboard to achieve the action of pressing the →↓←+○ on the gamepad.

1. Save this to your desktop as `test.lua`:
    ```lua
    SetDelayedFunctions(
       250, -- The following functions run with 250ms delay between them
       function ()
          -- You can either press and hold...
          GamePad.Simulate(GamePadControl.DPadRight, PressState.Press)
       end,
       function ()
          -- ... to manually release a button.
          GamePad.Simulate(GamePadControl.DPadRight, PressState.Release)
       end,
       function ()
          -- Or simply press and release (takes 50 ms to release)
          GamePad.Simulate(GamePadControl.DPadDown, PressState.PressAndRelease)
       end,
       function ()
          GamePad.Simulate(GamePadControl.DPadLeft, PressState.PressAndRelease)
       end,
       function ()
          GamePad.Simulate(GamePadControl.B, PressState.PressAndRelease)
       end
    )
    ```
2. In KeyToJoy click "Create New Mapping"
3. Choose the trigger "Keyboard Event"
4. Press "F"
5. Select "Release" (so the script will only run once on key release)
6. Choose the action "Lua Script Action"
7. Untick "Direct Input" (so we can select a script from file)
8. Browse to the `test.lua` file
9. Save the mapping.

![image](https://user-images.githubusercontent.com/2738114/177006114-1ffafa7e-2f94-43d4-bddc-1bcca7c51344.png)

Now when you Enable the mappings (checkbox in the top right of KeyToJoy) you can run that Lua script by pressing "F" on your keyboard.

All available GamePadControls are:
```
GamePadControl.None
GamePadControl.DPadUp
GamePadControl.DPadDown
GamePadControl.DPadLeft
GamePadControl.DPadRight
GamePadControl.Start
GamePadControl.Back
GamePadControl.LeftStickClick
GamePadControl.RightStickClick
GamePadControl.LeftShoulder
GamePadControl.RightShoulder
GamePadControl.Guide
GamePadControl.A
GamePadControl.B
GamePadControl.X
GamePadControl.Y
GamePadControl.LeftTrigger
GamePadControl.RightTrigger
GamePadControl.LeftStickLeft
GamePadControl.LeftStickRight
GamePadControl.LeftStickUp
GamePadControl.LeftStickDown
GamePadControl.RightStickLeft
GamePadControl.RightStickRight
GamePadControl.RightStickUp
GamePadControl.RightStickDown
GamePadControl.LeftStickAsAnalog
GamePadControl.RightStickAsAnalog
GamePadControl.DPadAsAnalog
```

**Comment by nxoet** [comment]
God, you are so kind ,what a detailed tutorial. Thank you so much.
