### ISSUE TITLE
no "start" and "menu" button

### ISSUE THREAD

**Issue by nxoet** [luttje/KeyToJoy#4]
games need these button

**Comment by luttje** [comment]
Since this was pretty easy to do I added this in a new release: https://github.com/luttje/KeyToJoy/releases/tag/0.3.4

**Comment by nxoet** [comment]
> Since this was pretty easy to do I added this in a new release: https://github.com/luttje/KeyToJoy/releases/tag/0.3.4

thanks, but theres a problem, i cant find anywhere to bind the "start" and "menu", they just show in the picture,but not in the left bind lists.

**Comment by luttje** [comment]
Hmm good that you mention this, I'll make a new issue for this bug.

The workaround is to go to `Key2Joy Presets`  in your Windows documents directory and remove existing presets.
